suprisonly it works
punixcorn/foo pull request #5
Opened 2023-04-16 15:27 UTC by Dragonixj

made a code for printing a kite shape

2023-04-17 04:04 UTC, punixcorn requested changes

2023-04-17 04:04 UTC, punixcorn commented on hex.c
> +
you didnt check if the number input was 0 or a neg number

2023-04-17 05:48 UTC, Dragonixj commented
du du du

2023-04-18 09:01 UTC, punixcorn commented
looks fixed

2023-04-18 09:01 UTC, punixcorn approved these changes

2023-04-18 09:01 UTC, merged